FROM golang:1.25 AS build

COPY go.mod go.sum /src/
COPY frontend /src/frontend

ENV CGO_ENABLED=0
RUN cd /src && go build -o /frontend frontend/main.go

FROM alpine:3.20

COPY --from=build /frontend /frontend
COPY frontend/templates /templates
COPY frontend/static /static

ENTRYPOINT ["/frontend"]
